// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// FinanceDocDao is an autogenerated mock type for the FinanceDocDao type
type FinanceDocDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, doc
func (_m *FinanceDocDao) Create(ctx context.Context, doc *model.FinanceDoc) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.FinanceDoc) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsByProjectID provides a mock function with given fields: ctx, projectID
func (_m *FinanceDocDao) ExistsByProjectID(ctx context.Context, projectID int64) (bool, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByProjectID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDocID provides a mock function with given fields: ctx, docID
func (_m *FinanceDocDao) GetByDocID(ctx context.Context, docID string) (*model.FinanceDoc, error) {
	ret := _m.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for GetByDocID")
	}

	var r0 *model.FinanceDoc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.FinanceDoc, error)); ok {
		return rf(ctx, docID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.FinanceDoc); ok {
		r0 = rf(ctx, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FinanceDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, size, status, creator
func (_m *FinanceDocDao) List(ctx context.Context, page int, size int, status string, creator string) ([]*model.FinanceDoc, int64, error) {
	ret := _m.Called(ctx, page, size, status, creator)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.FinanceDoc
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]*model.FinanceDoc, int64, error)); ok {
		return rf(ctx, page, size, status, creator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*model.FinanceDoc); ok {
		r0 = rf(ctx, page, size, status, creator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FinanceDoc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) int64); ok {
		r1 = rf(ctx, page, size, status, creator)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string) error); ok {
		r2 = rf(ctx, page, size, status, creator)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateContent provides a mock function with given fields: ctx, docID, description, applicationDetail
func (_m *FinanceDocDao) UpdateContent(ctx context.Context, docID string, description string, applicationDetail []byte) error {
	ret := _m.Called(ctx, docID, description, applicationDetail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) error); ok {
		r0 = rf(ctx, docID, description, applicationDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, docID, status, remark
func (_m *FinanceDocDao) UpdateStatus(ctx context.Context, docID string, status string, remark string) error {
	ret := _m.Called(ctx, docID, status, remark)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, docID, status, remark)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFinanceDocDao creates a new instance of FinanceDocDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinanceDocDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinanceDocDao {
	mock := &FinanceDocDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
