// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// FinancePaymentDao is an autogenerated mock type for the FinancePaymentDao type
type FinancePaymentDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, payment
func (_m *FinancePaymentDao) Create(ctx context.Context, tx *gorm.DB, payment *model.FinancePayment) error {
	ret := _m.Called(ctx, tx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.FinancePayment) error); ok {
		r0 = rf(ctx, tx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByPaymentIDAndDocID provides a mock function with given fields: ctx, paymentID, docID
func (_m *FinancePaymentDao) GetByPaymentIDAndDocID(ctx context.Context, paymentID string, docID string) (*model.FinancePayment, error) {
	ret := _m.Called(ctx, paymentID, docID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPaymentIDAndDocID")
	}

	var r0 *model.FinancePayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.FinancePayment, error)); ok {
		return rf(ctx, paymentID, docID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.FinancePayment); ok {
		r0 = rf(ctx, paymentID, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FinancePayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, paymentID, docID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByDocID provides a mock function with given fields: ctx, docID
func (_m *FinancePaymentDao) ListByDocID(ctx context.Context, docID string) ([]*model.FinancePayment, error) {
	ret := _m.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for ListByDocID")
	}

	var r0 []*model.FinancePayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.FinancePayment, error)); ok {
		return rf(ctx, docID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.FinancePayment); ok {
		r0 = rf(ctx, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FinancePayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFinancePaymentDao creates a new instance of FinancePaymentDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinancePaymentDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinancePaymentDao {
	mock := &FinancePaymentDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
