// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// IssueRequestDao is an autogenerated mock type for the IssueRequestDao type
type IssueRequestDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IssueRequestDao) Create(ctx context.Context, request *model.IssueRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.IssueRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IssueRequestDao) GetByID(ctx context.Context, id int64) (*model.IssueRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.IssueRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.IssueRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.IssueRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IssueRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDForUpdate provides a mock function with given fields: ctx, tx, id
func (_m *IssueRequestDao) GetByIDForUpdate(ctx context.Context, tx *gorm.DB, id int64) (*model.IssueRequest, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUpdate")
	}

	var r0 *model.IssueRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) (*model.IssueRequest, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) *model.IssueRequest); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IssueRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByProjectID provides a mock function with given fields: ctx, projectID, page, size, status, creator
func (_m *IssueRequestDao) ListByProjectID(ctx context.Context, projectID int64, page int, size int, status string, creator string) ([]*model.IssueRequest, int64, error) {
	ret := _m.Called(ctx, projectID, page, size, status, creator)

	if len(ret) == 0 {
		panic("no return value specified for ListByProjectID")
	}

	var r0 []*model.IssueRequest
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int, string, string) ([]*model.IssueRequest, int64, error)); ok {
		return rf(ctx, projectID, page, size, status, creator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int, string, string) []*model.IssueRequest); ok {
		r0 = rf(ctx, projectID, page, size, status, creator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.IssueRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int, string, string) int64); ok {
		r1 = rf(ctx, projectID, page, size, status, creator)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int, string, string) error); ok {
		r2 = rf(ctx, projectID, page, size, status, creator)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListDistinctProjectIDsByStatus provides a mock function with given fields: ctx, status
func (_m *IssueRequestDao) ListDistinctProjectIDsByStatus(ctx context.Context, status string) ([]int64, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for ListDistinctProjectIDsByStatus")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]int64, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []int64); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkOngoing provides a mock function with given fields: ctx, tx, id
func (_m *IssueRequestDao) MarkOngoing(ctx context.Context, tx *gorm.DB, id int64) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkOngoing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFields provides a mock function with given fields: ctx, id, voucherType, unit, amount, remark
func (_m *IssueRequestDao) UpdateFields(ctx context.Context, id int64, voucherType string, unit string, amount string, remark string) error {
	ret := _m.Called(ctx, id, voucherType, unit, amount, remark)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFields")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string) error); ok {
		r0 = rf(ctx, id, voucherType, unit, amount, remark)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusInTx provides a mock function with given fields: ctx, tx, id, fromStatus, toStatus, remark
func (_m *IssueRequestDao) UpdateStatusInTx(ctx context.Context, tx *gorm.DB, id int64, fromStatus string, toStatus string, remark string) error {
	ret := _m.Called(ctx, tx, id, fromStatus, toStatus, remark)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string, string, string) error); ok {
		r0 = rf(ctx, tx, id, fromStatus, toStatus, remark)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIssueRequestDao creates a new instance of IssueRequestDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssueRequestDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueRequestDao {
	mock := &IssueRequestDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
