// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// IssueBudgetDao is an autogenerated mock type for the IssueBudgetDao type
type IssueBudgetDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, budget
func (_m *IssueBudgetDao) Create(ctx context.Context, tx *gorm.DB, budget *model.IssueBudget) error {
	ret := _m.Called(ctx, tx, budget)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.IssueBudget) error); ok {
		r0 = rf(ctx, tx, budget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByIssueRequestID provides a mock function with given fields: ctx, issueRequestID
func (_m *IssueBudgetDao) GetByIssueRequestID(ctx context.Context, issueRequestID int64) (*model.IssueBudget, error) {
	ret := _m.Called(ctx, issueRequestID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIssueRequestID")
	}

	var r0 *model.IssueBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.IssueBudget, error)); ok {
		return rf(ctx, issueRequestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.IssueBudget); ok {
		r0 = rf(ctx, issueRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.IssueBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, issueRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIssueBudgetDao creates a new instance of IssueBudgetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssueBudgetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueBudgetDao {
	mock := &IssueBudgetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
