// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// PaymentConfigDao is an autogenerated mock type for the PaymentConfigDao type
type PaymentConfigDao struct {
	mock.Mock
}

// GetByPayAddress provides a mock function with given fields: ctx, payAddress
func (_m *PaymentConfigDao) GetByPayAddress(ctx context.Context, payAddress string) (*model.PaymentConfig, error) {
	ret := _m.Called(ctx, payAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetByPayAddress")
	}

	var r0 *model.PaymentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PaymentConfig, error)); ok {
		return rf(ctx, payAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PaymentConfig); ok {
		r0 = rf(ctx, payAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PaymentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, payAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx
func (_m *PaymentConfigDao) ListAll(ctx context.Context) ([]*model.PaymentConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*model.PaymentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.PaymentConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.PaymentConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PaymentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentConfigDao creates a new instance of PaymentConfigDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentConfigDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentConfigDao {
	mock := &PaymentConfigDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
