// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// ProjectBudgetDao is an autogenerated mock type for the ProjectBudgetDao type
type ProjectBudgetDao struct {
	mock.Mock
}

// ApplyApproveIssued provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) ApplyApproveIssued(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplyApproveIssued")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApplyDistributionDeductAvailable provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) ApplyDistributionDeductAvailable(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDistributionDeductAvailable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApplyDistributionIssued provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) ApplyDistributionIssued(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDistributionIssued")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApplyDistributionRefund provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) ApplyDistributionRefund(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDistributionRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApplyRejectRelease provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) ApplyRejectRelease(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplyRejectRelease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApplySubmitWithhold provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) ApplySubmitWithhold(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for ApplySubmitWithhold")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BatchCreate provides a mock function with given fields: ctx, tx, budgets
func (_m *ProjectBudgetDao) BatchCreate(ctx context.Context, tx *gorm.DB, budgets []*model.ProjectBudget) error {
	ret := _m.Called(ctx, tx, budgets)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []*model.ProjectBudget) error); ok {
		r0 = rf(ctx, tx, budgets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountByFinanceDocID provides a mock function with given fields: ctx, docID
func (_m *ProjectBudgetDao) CountByFinanceDocID(ctx context.Context, docID string) (int64, error) {
	ret := _m.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for CountByFinanceDocID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, docID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, docID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDocIDVoucherTypeUnit provides a mock function with given fields: ctx, docID, voucherType, unit
func (_m *ProjectBudgetDao) GetByDocIDVoucherTypeUnit(ctx context.Context, docID string, voucherType string, unit string) (*model.ProjectBudget, error) {
	ret := _m.Called(ctx, docID, voucherType, unit)

	if len(ret) == 0 {
		panic("no return value specified for GetByDocIDVoucherTypeUnit")
	}

	var r0 *model.ProjectBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.ProjectBudget, error)); ok {
		return rf(ctx, docID, voucherType, unit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.ProjectBudget); ok {
		r0 = rf(ctx, docID, voucherType, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProjectBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, docID, voucherType, unit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByProjectIDVoucherTypeUnit provides a mock function with given fields: ctx, projectID, voucherType, unit
func (_m *ProjectBudgetDao) GetByProjectIDVoucherTypeUnit(ctx context.Context, projectID int64, voucherType string, unit string) (*model.ProjectBudget, error) {
	ret := _m.Called(ctx, projectID, voucherType, unit)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectIDVoucherTypeUnit")
	}

	var r0 *model.ProjectBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (*model.ProjectBudget, error)); ok {
		return rf(ctx, projectID, voucherType, unit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) *model.ProjectBudget); ok {
		r0 = rf(ctx, projectID, voucherType, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProjectBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, projectID, voucherType, unit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasAvailableForDistribution provides a mock function with given fields: ctx, projectID, voucherType, unit, amount
func (_m *ProjectBudgetDao) HasAvailableForDistribution(ctx context.Context, projectID int64, voucherType string, unit string, amount string) (bool, error) {
	ret := _m.Called(ctx, projectID, voucherType, unit, amount)

	if len(ret) == 0 {
		panic("no return value specified for HasAvailableForDistribution")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string) (bool, error)); ok {
		return rf(ctx, projectID, voucherType, unit, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string) bool); ok {
		r0 = rf(ctx, projectID, voucherType, unit, amount)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string) error); ok {
		r1 = rf(ctx, projectID, voucherType, unit, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockByID provides a mock function with given fields: ctx, tx, budgetID
func (_m *ProjectBudgetDao) LockByID(ctx context.Context, tx *gorm.DB, budgetID int64) (*model.ProjectBudget, error) {
	ret := _m.Called(ctx, tx, budgetID)

	if len(ret) == 0 {
		panic("no return value specified for LockByID")
	}

	var r0 *model.ProjectBudget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) (*model.ProjectBudget, error)); ok {
		return rf(ctx, tx, budgetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) *model.ProjectBudget); ok {
		r0 = rf(ctx, tx, budgetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProjectBudget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int64) error); ok {
		r1 = rf(ctx, tx, budgetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTotalAndAvailableAmount provides a mock function with given fields: ctx, tx, budgetID, amount
func (_m *ProjectBudgetDao) UpdateTotalAndAvailableAmount(ctx context.Context, tx *gorm.DB, budgetID int64, amount string) error {
	ret := _m.Called(ctx, tx, budgetID, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTotalAndAvailableAmount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, budgetID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProjectBudgetDao creates a new instance of ProjectBudgetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectBudgetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectBudgetDao {
	mock := &ProjectBudgetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
