// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// ProjectDao is an autogenerated mock type for the ProjectDao type
type ProjectDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, project
func (_m *ProjectDao) Create(ctx context.Context, project *model.Project) (int64, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Project) (int64, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Project) int64); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ProjectDao) GetByID(ctx context.Context, id int64) (*model.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, size
func (_m *ProjectDao) List(ctx context.Context, page int, size int) ([]*model.Project, int64, error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Project
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Project, int64, error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Project); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, size)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByIDs provides a mock function with given fields: ctx, ids
func (_m *ProjectDao) ListByIDs(ctx context.Context, ids []int64) ([]*model.Project, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListByIDs")
	}

	var r0 []*model.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]*model.Project, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []*model.Project); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProjectDao creates a new instance of ProjectDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectDao {
	mock := &ProjectDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
