// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// RewardRequestDao is an autogenerated mock type for the RewardRequestDao type
type RewardRequestDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tx, request
func (_m *RewardRequestDao) Create(ctx context.Context, tx *gorm.DB, request *model.RewardRequest) error {
	ret := _m.Called(ctx, tx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *model.RewardRequest) error); ok {
		r0 = rf(ctx, tx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByClientRefID provides a mock function with given fields: ctx, clientRefID
func (_m *RewardRequestDao) GetByClientRefID(ctx context.Context, clientRefID string) (*model.RewardRequest, error) {
	ret := _m.Called(ctx, clientRefID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientRefID")
	}

	var r0 *model.RewardRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.RewardRequest, error)); ok {
		return rf(ctx, clientRefID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.RewardRequest); ok {
		r0 = rf(ctx, clientRefID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RewardRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientRefID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RewardRequestDao) GetByID(ctx context.Context, id int64) (*model.RewardRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.RewardRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.RewardRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.RewardRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RewardRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, tx, id, status
func (_m *RewardRequestDao) UpdateStatus(ctx context.Context, tx *gorm.DB, id int64, status string) error {
	ret := _m.Called(ctx, tx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64, string) error); ok {
		r0 = rf(ctx, tx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRewardRequestDao creates a new instance of RewardRequestDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRewardRequestDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *RewardRequestDao {
	mock := &RewardRequestDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
