// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nusiss-capstone-project/reward-mservice/server/repository/model"
)

// TemplateDao is an autogenerated mock type for the TemplateDao type
type TemplateDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, template
func (_m *TemplateDao) Create(ctx context.Context, template *model.Template) (int64, error) {
	ret := _m.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Template) (int64, error)); ok {
		return rf(ctx, template)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Template) int64); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Template) error); ok {
		r1 = rf(ctx, template)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TemplateDao) GetByID(ctx context.Context, id int64) (*model.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Template); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, size, status
func (_m *TemplateDao) List(ctx context.Context, page int, size int, status string) ([]*model.Template, int64, error) {
	ret := _m.Called(ctx, page, size, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Template
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) ([]*model.Template, int64, error)); ok {
		return rf(ctx, page, size, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []*model.Template); ok {
		r0 = rf(ctx, page, size, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) int64); ok {
		r1 = rf(ctx, page, size, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, page, size, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, title, config
func (_m *TemplateDao) Update(ctx context.Context, id int64, title string, config []byte) error {
	ret := _m.Called(ctx, id, title, config)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, []byte) error); ok {
		r0 = rf(ctx, id, title, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, fromStatus, toStatus
func (_m *TemplateDao) UpdateStatus(ctx context.Context, id int64, fromStatus string, toStatus string) error {
	ret := _m.Called(ctx, id, fromStatus, toStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, id, fromStatus, toStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTemplateDao creates a new instance of TemplateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateDao {
	mock := &TemplateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
